services:
  - type: web
    name: pga-prediction-app
    runtime: python
    rootDir: pga_app
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
